# Generated by Django 4.2 on 2024-06-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=40),
        ),
    ]
